resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

# configMapGenerator:
# - name: manager-config
#   files:
#   - controller_manager_config.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: quay.io/gatekeeper/gatekeeper-operator
  newTag: v0.3.0-candidate.2
