apiVersion: v1
kind: Pod
metadata:
  name: affinity-pod
  labels:
    auditKey: auditValue
spec:
  containers:
  - name: affinity-pod
    image: busybox
    command: ["/bin/sh", "-c", "sleep INF"]
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
  nodeSelector:
    topology.kubernetes.io/zone: test
    region: EMEA
