apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
- patch: |-
    - op: add
      path: /rules/-
      value:
        apiGroups:
          - security.openshift.io
        resourceNames:
          - anyuid
        resources:
          - securitycontextconstraints
        verbs:
          - use
  target:
    group: rbac.authorization.k8s.io
    kind: ClusterRole
    name: manager-role
    version: v1
