
name: Slash Command Dispatch

on:
  issue_comment:
    types: [ created, edited ]

jobs:
  slashCommandDispatch:
    runs-on: ubuntu-18.04
    steps:
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v2
        with:
          token: ${{ secrets.ACTIONS_BOT_TOKEN }}
          commands: |
            deploy
            integration-test
            build-docs

  helloWorld:
    runs-on: ubuntu-18.04
    steps:
      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: hooray

      - name: Create URL to the run output
        id: vars
        run: echo ::set-output name=run-url::https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
          body: |
            Hello @${{ github.event.client_payload.github.actor }}!
            [Click here to see the command run output][1]
            [1]: ${{ steps.vars.outputs.run-url }}

  help:
    runs-on: ubuntu-18.04
    steps:
      - name: Update comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.ACTIONS_BOT_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          body: |
            > Command | Description
            > --- | ---
            > /hello-world | Receive a greeting from the world
            > /ping [\<args\> ...] | Echos back a list of arguments
            > /hello-world-local | Receive a greeting from the world (local execution)
            > /ping-local [\<args\> ...] | Echos back a list of arguments (local execution)
          reaction-type: hooray
