name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  main:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        go: [ '1.15' ]
    name: Go ${{ matrix.go }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      id: go
      with:
        go-version: ${{ matrix.go }}

    - name: Verify modules
      run: go mod verify

    - name: Verify format
      run: |
        make fmt
        git diff --exit-code

    - name: Verify manifests
      run: |
        make manifests
        git diff --exit-code

    - name: Verify imported manifests
      run: |
        make import-manifests
        git diff --exit-code

    - name: Verify bindata
      run: |
        make verify-bindata

    - name: Verify bundle
      run: |
        make bundle
        git diff --exit-code

    - name: Create K8s KinD Cluster
      run: kind create cluster

    - name: Build and Push Test Container Image to KIND node
      run: |
        make docker-build IMG=localhost:5000/gatekeeper-operator:$GITHUB_SHA
        kind load docker-image localhost:5000/gatekeeper-operator:$GITHUB_SHA

    - name: Unit and Integration Tests
      run: make test

    - name: E2E Tests
      run: |
        make deploy-ci NAMESPACE=mygatekeeper IMG=localhost:5000/gatekeeper-operator:$GITHUB_SHA
        sleep 60
        make test-e2e
        kubectl delete --wait namespace mygatekeeper

    - name: Gatekeeper E2E Tests
      run: |
        sudo apt-get install -y bats
        make deploy-ci NAMESPACE=gatekeeper-system IMG=localhost:5000/gatekeeper-operator:$GITHUB_SHA
        make test-gatekeeper-e2e

    - name: OLM E2E Tests
      run: |
        kind delete cluster
        kind create cluster
        make kind-deploy-olm
        make bundle IMG=localhost:5000/gatekeeper-operator:$GITHUB_SHA
        make bundle-build REPO=localhost:5000 VERSION=$GITHUB_SHA
        kind load docker-image localhost:5000/gatekeeper-operator-bundle:$GITHUB_SHA
        make bundle-index-build REPO=localhost:5000 VERSION=$GITHUB_SHA
        kind load docker-image localhost:5000/gatekeeper-operator-bundle-index:$GITHUB_SHA
        make set-olm-e2e-img INDEX_IMAGE=localhost:5000/gatekeeper-operator/gatekeeper-operator-bundle-index:$GITHUB_SHA
        make test-e2e-olm
