name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  main:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        go: [ '1.15' ]
    name: Go ${{ matrix.go }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      id: go
      with:
        go-version: ${{ matrix.go }}

    - name: Verify modules
      run: go mod verify

    - name: Verify format
      run: |
        make fmt
        git diff --exit-code

    - name: Verify manifests
      run: |
        make manifests
        git diff --exit-code

    - name: Verify imported manifests
      run: |
        make import-manifests
        git diff --exit-code

    - name: Verify bindata
      run: |
        make verify-bindata

    - name: Create K8s KinD Cluster
      run: kind create cluster

    - name: Build and Push Test Container Image
      run: |
        make docker-build IMG=localhost:5000/gatekeeper-operator:$GITHUB_SHA
        kind load docker-image localhost:5000/gatekeeper-operator:$GITHUB_SHA

    - name: Unit and Integration Tests
      run: make test

    - name: Deploy Gatekeeper Operator
      run: |
        make install
        make deploy NAMESPACE=mygatekeeper IMG=localhost:5000/gatekeeper-operator:$GITHUB_SHA

    - name: Gatekeeper Operator E2E Tests
      run: |
        make test-e2e
        kubectl delete namespace mygatekeeper

    - name: Gatekeeper E2E Tests
      run: |
        # BATS tests expect 'gatekeeper-system' namespace.
        make deploy IMG=localhost:5000/gatekeeper-operator:$GITHUB_SHA
        sudo apt-get install -y bats
        make test-gatekeeper-e2e
